import { execFileSync } from "node:child_process";
import fs from "node:fs/promises";
import { homedir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import esbuild from "esbuild";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const output = path.resolve(root, "out/vorbis.wasm");
const javascriptOutput = path.resolve(root, "out/vorbis.wasm.js");

// eslint-disable-next-line unicorn/consistent-boolean-name
async function fileExists(path: string) {
    try {
        await fs.access(path);
        return true;
    } catch {
        return false;
    }
}

async function findEmcc() {
    // Attempt to find emcc
    const candidates = [
        process.env.EMCC,
        process.env.EMSDK === undefined
            ? undefined
            : path.resolve(process.env.EMSDK, "upstream/emscripten/emcc"),
        path.resolve(homedir(), "emsdk/upstream/emscripten/emcc"),
        "emcc"
    ];

    for (const candidate of candidates) {
        if (
            candidate !== undefined &&
            (candidate === "emcc" || (await fileExists(candidate)))
        ) {
            return candidate;
        }
    }

    throw new Error("Could not find emcc!");
}

// Remove dist if exists
await fs.rm(path.resolve(root, "dist"), { recursive: true, force: true });
await fs.mkdir(path.resolve(root, "dist"), { recursive: true });
await fs.mkdir(path.resolve(root, "out"), { recursive: true });

execFileSync(
    await findEmcc(),
    [
        path.resolve(root, "wasm/vorbis_wrapper.c"),

        // O3 means "optimize for size"
        "-O3",
        // Flto means "link-time optimization"
        "-flto",

        "--no-entry",

        // Standalone, we glue it ourselves
        "-sSTANDALONE_WASM=1",
        // Unlimited heap size
        "-sALLOW_MEMORY_GROWTH=1",

        // Lots of memory
        "-sMAXIMUM_MEMORY=2147483648",
        "-sMALLOC=dlmalloc",

        // We don't use files, stdout, filesystem APIs, etc.
        "-sFILESYSTEM=0",

        // We don't need Emscripten's JS runtime.
        "-sEXPORTED_RUNTIME_METHODS=[]",

        // C ABI exposed directly to our handwritten TypeScript/JS.
        "-sEXPORTED_FUNCTIONS=_vorbis_decode,_vorbis_free,_malloc,_free",

        "-o",
        output
    ],
    {
        cwd: root,
        stdio: "inherit"
    }
);
const bin = await fs.readFile(output);

const base64 = bin.toString("base64");
await fs.writeFile(
    javascriptOutput,
    `// Generated by scripts/build-wasm.ts.\nexport default ${JSON.stringify(base64)};\n`
);

// Build esbuild
await esbuild.build({
    entryPoints: [path.resolve(root, "src/index.ts")],
    bundle: true,
    minify: true,
    treeShaking: true,
    outfile: path.resolve(root, "dist/index.js"),
    format: "esm",
    platform: "neutral",
    target: "es2022",
    tsconfig: path.resolve(root, "tsconfig.json"),
    logLevel: "info"
});

// Emit type declarations
execFileSync("tsc", ["-p", path.resolve(root, "tsconfig.build.json")], {
    cwd: root,
    stdio: "inherit"
});
