name: Publish the npm package

on:
    push:
        tags:
            - "v*"

    workflow_dispatch:

jobs:
    publish-npm:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write
            id-token: write

        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

            - name: Setup Emscripten
              uses: emscripten-core/setup-emsdk@667eb33f24e84e7f362c16d8d7fff0629a73e15e # v15
              with:
                  version: 6.0.6
                  actions-cache-folder: .emsdk-cache

            - name: Setup Node
              uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
              with:
                  node-version: 24.19.0
                  registry-url: https://registry.npmjs.org

            - name: Install dependencies
              run: npm ci

            - name: Install Chromium
              run: npx playwright install --with-deps chromium

            - name: Build and test
              run: npm test

            - name: Publish to npm registry
              run: npm publish --provenance --access public --ignore-scripts
